import { Metadata } from 'next';
import { baseMetadata } from '@/lib/constants';
import HomePage from '@/pages/HomePage';

export const metadata: Metadata = {
	...baseMetadata,
	title: `Home - ${baseMetadata.title}`,
	description: 'Generated by create next app'
};

export default function Home() {
	return <HomePage />;
}
