name: Build the app
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  cache:
    name: Cache Dependencies and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache  # Node modules
            ~/.cache/playwright   # Playwright browsers
          key: ${{ runner.os }}-cache-${{ hashFiles('**/bun.lockb', 'package.json', 'src/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-bun-

  # Build
  build:
    name: Building the app...
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Install Playwright Browsers
        run: bun playwright install chromium --with-deps

      - name: Build
        run: bun run build

  #  Unit and E2E Test
  test:
    name: Unit/E2E Tests...
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Install Playwright Browsers
        run: bun playwright install chromium --with-deps

      - name: Running Unit Tests
        run: bun test:unit
        
      - name: Run Playwright tests
        env:
          CI: true
        run: bun test:e2e

