name: Build the app
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  # Build
  build:
    name: Building the app...
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

  #  Unit and E2E Test
  test:
    name: Unit/E2E Tests...
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install


      - name: Build
        run: bun run build

      - name: Running Unit Tests
        run: bun test:unit

      - name: Install Playwright Browsers
        run: bun playwright install --with-deps

      - name: Run Playwright tests
        run: bun test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
